# -*- coding: utf-8 -*-
"""movie_recommend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1se8YtT44dY2dVUD0j5buhyIkO8ZqjwPj
"""

# --- app.py ---
import streamlit as st
import pandas as pd
import pickle
from sklearn.metrics.pairwise import cosine_similarity

# ---------------------------------
# 🎬 Page Configuration
# ---------------------------------
st.set_page_config(page_title="🎥 Movie Recommendation Engine", layout="wide")
st.title("🎞️ Movie Recommendation Web Application")
st.write("Find movies similar to your favorite title!")

# ---------------------------------
# 📦 Load Pre-trained Model (Pickle)
# ---------------------------------
@st.cache_resource
def load_model():
    with open('movie_model.pkl', 'rb') as f:
        model = pickle.load(f)
    return model

model = load_model()

# Extract components
movies = model['movies']
tfidf = model['tfidf']
vector_matrix = model['vector_matrix']

# ---------------------------------
# 🧠 Recommendation Function
# ---------------------------------
def recommend(movie_name, n=5):
    if movie_name not in movies['title'].values:
        st.error("❌ Movie not found in dataset! Please select another title.")
        return pd.DataFrame()

    # Find the index of the selected movie
    index = movies[movies['title'] == movie_name].index[0]

    # Compute similarity for that single movie only
    movie_vector = vector_matrix[index]
    similarity_scores = cosine_similarity(movie_vector, vector_matrix).flatten()

    # Get top N similar movies (excluding itself)
    top_indices = similarity_scores.argsort()[-n-1:-1][::-1]

    # Return results
    recommended = movies.iloc[top_indices][['title', 'genres']]
    return recommended

# ---------------------------------
# 🎛️ Sidebar Controls
# ---------------------------------
st.sidebar.header("🎬 Choose Your Movie")
selected_movie = st.sidebar.selectbox(
    "Select a movie title:",
    options=sorted(movies['title'].unique())
)

num_recs = st.sidebar.slider("Number of Recommendations", 3, 10, 5)

# ---------------------------------
# 🎯 Display Recommendations
# ---------------------------------
if st.sidebar.button("🔍 Show Recommendations"):
    with st.spinner("Finding similar movies..."):
        results = recommend(selected_movie, num_recs)

    if not results.empty:
        st.success(f"Top {num_recs} movies similar to **{selected_movie}**:")
        st.dataframe(results, use_container_width=True)
else:
    st.info("👈 Select a movie and click **Show Recommendations** to begin.")

# ---------------------------------
# 🧾 Footer
# ---------------------------------
st.markdown("---")
st.caption("Built by **Yeluguri Rohan** | Powered by Streamlit & Scikit-learn")